export const SAMPLE_CONFIG = `# DumpVault config — generated by \`dumpvault init\`.
# Spec: docs/PRD.md §6.1

storage:
  path: ~/dumpvault/backups
  retention:
    keep_last: 7

# Optional. Remove this block to disable webhooks.
# notifications:
#   webhook: https://hooks.slack.com/services/XXX/YYY/ZZZ
#   on: [failure]              # or [failure, success]

scheduler:
  max_concurrent: 2            # global cap on parallel jobs
  jitter_seconds: 60           # +/- random delay to avoid thundering herd

databases:
  - name: prod-app
    engine: postgres
    host: db.example.com
    port: 5432
    user: backup_user
    password_env: PROD_PG_PASSWORD     # never inline secrets — use env var or *_file
    database: app
    schedule: "0 2 * * *"              # standard cron, or shorthand like "@daily"
    options:
      format: custom                   # pg_dump -Fc
      compress: 6                      # gzip level 1-9
`;
