export const SAMPLE_CONFIG = `# DumpVault config — generated by \`dumpvault init\`.
# Spec: docs/PRD.md §6.1

storage:
  path: ~/dumpvault/backups
  # Optional encryption at rest (AES-256-GCM). Generate a key with:
  #   dumpvault keygen --out ~/.dumpvault/master.key
  # encryption:
  #   enabled: true
  #   key_file: ~/.dumpvault/master.key
  retention:
    keep_last: 7         # always keep the 7 most recent dumps (any age)
    # keep_daily: 30     # plus the newest dump from each of the last 30 days
    # keep_weekly: 12    # plus the newest from each of the last 12 ISO weeks
    # keep_monthly: 12   # plus the newest from each of the last 12 months

# Optional. Remove this block to disable webhooks.
# notifications:
#   webhook: https://hooks.slack.com/services/XXX/YYY/ZZZ
#   on: [failure]              # or [failure, success]

scheduler:
  max_concurrent: 2            # global cap on parallel jobs
  jitter_seconds: 60           # +/- random delay to avoid thundering herd

databases:
  - name: prod-app
    engine: postgres                   # postgres | mysql
    host: db.example.com
    port: 5432
    user: backup_user
    password_env: PROD_PG_PASSWORD     # never inline secrets — use env var or *_file
    database: app
    schedule: "0 2 * * *"              # standard cron, or shorthand like "@daily"
    options:
      format: custom                   # pg_dump -Fc
      compress: 6                      # gzip level 1-9

  # Example MySQL / MariaDB target. Uncomment and edit.
  # - name: legacy-mysql
  #   engine: mysql
  #   host: mysql.example.com
  #   port: 3306
  #   user: backup_user
  #   password_env: LEGACY_MYSQL_PASSWORD
  #   database: app
  #   schedule: "@daily"
  #   options:
  #     single_transaction: true       # InnoDB-safe consistent dump
  #     routines: true                 # include stored procs / functions
  #     ssl_mode: REQUIRED             # for hosted services like PlanetScale
`;
